// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYfyCbEy7ZU1wyMuhXU52c8wcr8I2rhd4',
    appId: '1:366553761617:web:876a1fce8648e0694d7570',
    messagingSenderId: '366553761617',
    projectId: 'chating-application-2024',
    authDomain: 'chating-application-2024.firebaseapp.com',
    storageBucket: 'chating-application-2024.appspot.com',
    measurementId: 'G-K21GN8R998',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6g9I3SR0vTr67Ah0dT_1lAQRKLJb4jI',
    appId: '1:366553761617:android:e43a2aad49b8f0364d7570',
    messagingSenderId: '366553761617',
    projectId: 'chating-application-2024',
    storageBucket: 'chating-application-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-LHmQtYglKPjQmEwLHxqg-9XxxH4CMas',
    appId: '1:366553761617:ios:cbf1601d8146240e4d7570',
    messagingSenderId: '366553761617',
    projectId: 'chating-application-2024',
    storageBucket: 'chating-application-2024.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-LHmQtYglKPjQmEwLHxqg-9XxxH4CMas',
    appId: '1:366553761617:ios:cbf1601d8146240e4d7570',
    messagingSenderId: '366553761617',
    projectId: 'chating-application-2024',
    storageBucket: 'chating-application-2024.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYfyCbEy7ZU1wyMuhXU52c8wcr8I2rhd4',
    appId: '1:366553761617:web:be9b123a35ce45154d7570',
    messagingSenderId: '366553761617',
    projectId: 'chating-application-2024',
    authDomain: 'chating-application-2024.firebaseapp.com',
    storageBucket: 'chating-application-2024.appspot.com',
    measurementId: 'G-9F3Z6GSV5L',
  );
}
